# IronRDP dev tasks

# Run the wgpu client
dev *ARGS:
    cargo run {{ARGS}}

# Run tests (pass extra args after --)
test *ARGS:
    cargo nextest run {{ARGS}}

# Run clippy lints
lint:
    cargo clippy

# Format code
fmt:
    cargo fmt
